AZURE_OPENAI_API_KEY = "2RqPmZXkJFTihAPvhpr4UQtLWLeIeCgj4u7VUIcXJMo2651D3ZneJQQJ99BFACHYHv6XJ3w3AAAAACOGtmyP"
AZURE_INFERENCE_ENDPOINT = "https://chatgpt-resourc.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-4.1"
AZURE_API_VERSION = "2025-01-01-preview"